### ISSUE TITLE
Cypress-testrail got error before:spec event when run using cypress 13

### ISSUE THREAD

**Issue by ivanalami** [boxblinkracer/cypress-testrail#45]
Hi, i have problem with run cypress using cypress 13.

In my cypress, I setup `config.cypress.js` section `e2e` like this : 
```
e2e: {
    supportFile: "./cypress/support/e2e.js",
    specPattern: "./cypress/e2e/features/**/**/*.{js,jsx,ts,tsx,feature}",
    testIsolation: false,
    watchForFileChanges: false,
    experimentalSessionAndOrigin: false,

    async setupNodeEvents(on, config) {
      on('task', {
        async connectDB(query) {
          const client = new Client({
            user: process.env.PG_USER,
            password: process.env.PG_PWD,
            host: process.env.PG_HOST,
            database: process.env.PG_DBNAME,
            ssl: false,
            port: 5432
          })
          await client.connect()
          const res = await client.query(query)
          await client.end()
          return res.rows;
        }
      },
         'before:browser:launch', (browser, launchOptions) => {
          if (browser.name === 'chrome') {
            launchOptions.preferences.default['profile.default_content_setting_values.media_stream_camera'] = true
            launchOptions.preferences.default['profile.default_content_setting_values.media_stream_mic'] = true
            launchOptions.preferences.default['profile.default_content_setting_values.geolocation'] = true
            launchOptions.preferences.default['profile.default_content_setting_values.notifications'] = true
            launchOptions.args.push('--window-size=1280,720');
            launchOptions.args.push('--use-fake-device-for-media-stream');
            launchOptions.args.push('--no-sandbox');
            launchOptions.args.push('--disable-dev-shm-usage');
            launchOptions.args.push('--js-flags=--expose-gc');
          }
        },
      )
      await preprocessor.addCucumberPreprocessorPlugin(on, config);
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin.default(config)],
        })
      );
      new TestRailReporter(on, config, customComment).register();
      return config;
    }
  },
  ```
  
  after that config I run cypress in CI like this :
  ```
  CYPRESS_TESTRAIL_DOMAIN=??? \
CYPRESS_TESTRAIL_USERNAME=??? \
CYPRESS_TESTRAIL_PASSWORD=??? \
CYPRESS_TESTRAIL_PROJECT_ID=18 \
CYPRESS_TESTRAIL_SUITE_ID=35 \
CYPRESS_TESTRAIL_RUN_NAME='Cypress Develop  \
CYPRESS_TESTRAIL_SCREENSHOTS=true \
npx cypress run --browser=chrome --env tags='@test'
```

and  got error like this : 
```
An error was thrown in your plugins file while executing the handler for the before:spec event.

The error we received was:

Error: Unexpected state in beforeSpecHandler: test-finished (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (/home/alami/Documents/git/mina-alami/e2e/node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:9:12)
    at beforeSpecHandler (/home/alami/Documents/git/mina-alami/e2e/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:190:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```
 
 
 if I disable this line `new TestRailReporter(on, config, customComment).register();` , no error show. 
 
 Can someone help me whats wrong in my config?

**Comment by boxblinkracer** [comment]
Hi

thank you for this

i wasnt able to reproduce this
could you maybe create a small sample on github and share the repo with me
then i can play around with it

thank you :)
