### ISSUE TITLE
Running multiple spec files at once is throwing an error from cucumber plugin

### ISSUE THREAD

**Issue by saiDEE12** [boxblinkracer/cypress-testrail#50]
I have done the configuration and it is working as expected for a signle  feature file. but when trying to run multiple feature at a time, after completion of running one feature file, it is throwing below errors.
command used for running
An error was thrown in your plugins file while executing the handler for the before:spec event.
**The error we received was:
Error: Unexpected state in beforeSpecHandler: test-finished (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (D:\Oct19TestRailIntegration\unity-hrq-automation-tests\node_modules\@badeball\cypress-cucumber-preprocessor\dist\helpers\error.js:9:12)
    at beforeSpecHandler (D:\Oct19TestRailIntegration\unity-hrq-automation-tests\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:190:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)**

**Comment by boxblinkracer** [comment]
Hi there
so with v2.10.0 i've officially checked the cucumber plugin
can you try it again with the README descriptions? maybe you also need the cypress-on-fix plugin that is new described?

thank you for trying it again :)
