### ISSUE TITLE
Randomly fails to update test results

### ISSUE THREAD

**Issue by kasunalwis** [boxblinkracer/cypress-testrail#7]
Randomly I'm seeing the following error in  `after:spec event` and causing it to fail the entire test.

`Version - 2.3.1`

An error was thrown in your plugins file while executing the handler for the after:spec event.

The error we received was:

TypeError: Cannot read properties of undefined (reading 'status')
 at /usr/src/app/node_modules/cypress-testrail/src/components/TestRail/ApiClient.js:155:51
 at processTicksAndRejections (node:internal/process/task_queues:96:5)
 at async Promise.all (index 2)
 at async Reporter._sendSpecResults (/usr/src/app/node_modules/cypress-testrail/src/Reporter.js:222:9)
 at async Reporter._afterSpec (/usr/src/app/node_modules/cypress-testrail/src/Reporter.js:149:9)
 at async Object.handler (/usr/src/app/node_modules/cypress-testrail/src/Reporter.js:58:13)

script returned exit code 1

![Screenshot 2022-12-05 at 18 29 17](https://user-images.githubusercontent.com/11239934/205703707-879f161d-851a-4782-a76b-d8a760ba31e4.png)

**Comment by boxblinkracer** [comment]
hi
v2.4.0 has been released. it should not completely break anymore and have better outputs
let me know if still something fails

thank you for your help

**Comment by kasunalwis** [comment]
Hey @boxblinkracer, Thank you very much for your quick response. Will update to `v2.4.0` and get back if error occurs.
